id: P948E06F4
initial_creation_type: input
source_metadata:
  title: Magnetizing Series
  language: zh
  description: 'Texts on the theme of magnetizing or bringing under one’s control
    (dbang du sdud pa):'
  volume:
    88f4cc8c60fa4f7bbc36a618222a661f:
      title: Magnetizing (Wangdü) Prayer
      parent: Prayers
    8d509ce03b1042dca3eaacdf4af78ef8:
      title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All
        that Appears and Exists'
      parent: Prayers
    4bbb3199b061442594c73364e7ec0093:
      title: 'Swift Enchantment of the Three Realms: A Sādhana of Red Tārā'
      parent: Sādhanas
created_at: '2022-03-01T04:30:45.116516'
last_modified_at: '2022-03-01T04:30:45.116518'
